"""Script to generate the remaining YAML templates for the IPO Draft Engine."""
import yaml
import os

TEMPLATES_DIR = os.path.dirname(__file__)

TEMPLATES = [
    {
        "id": "competitive-strengths",
        "section_name": "Competitive Strengths",
        "display_order": 8,
        "description": "Key competitive advantages and differentiators of the company.",
        "knowledge_mapping": [
            {"category": "business", "fields": ["competitive_strengths", "unique_selling_proposition", "market_position"]},
            {"category": "financials", "fields": ["revenue_growth", "ebitda_margin"]},
        ],
        "validation_rules": [
            {"field": "business.competitive_strengths", "required": True, "description": "Competitive strengths"},
        ],
        "prompt_template_path": "prompts/competitive-strengths.md",
        "output_format": "markdown",
        "dependencies": ["business-overview"],
        "estimated_pages": 3,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018",
    },
    {
        "id": "business-strategy",
        "section_name": "Business Strategy",
        "display_order": 9,
        "description": "Future growth plans, strategic initiatives, and expansion roadmap.",
        "knowledge_mapping": [
            {"category": "business", "fields": ["growth_strategy", "expansion_plans", "capex_plans", "product_pipeline"]},
            {"category": "issue", "fields": ["objects_of_issue"]},
        ],
        "validation_rules": [
            {"field": "business.growth_strategy", "required": True, "description": "Strategic growth plans"},
        ],
        "prompt_template_path": "prompts/business-strategy.md",
        "output_format": "markdown",
        "dependencies": ["business-overview"],
        "estimated_pages": 3,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018",
    },
    {
        "id": "company-history",
        "section_name": "Company History",
        "display_order": 10,
        "description": "Key milestones, corporate history, and events in the company's evolution.",
        "knowledge_mapping": [
            {"category": "company", "fields": ["incorporation_date", "key_milestones", "major_events", "corporate_restructuring"]},
        ],
        "validation_rules": [
            {"field": "company.incorporation_date", "required": True, "description": "Date of incorporation"},
            {"field": "company.key_milestones", "required": False, "description": "Key milestones"},
        ],
        "prompt_template_path": "prompts/company-history.md",
        "output_format": "markdown",
        "dependencies": ["company-overview"],
        "estimated_pages": 2,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018",
    },
    {
        "id": "products-services",
        "section_name": "Products & Services",
        "display_order": 11,
        "description": "Detailed description of all products and services offered by the company.",
        "knowledge_mapping": [
            {"category": "business", "fields": ["products", "services", "product_portfolio", "product_pricing", "product_pipeline"]},
        ],
        "validation_rules": [
            {"field": "business.products", "required": True, "description": "Product portfolio"},
        ],
        "prompt_template_path": "prompts/products-services.md",
        "output_format": "markdown",
        "dependencies": ["business-overview"],
        "estimated_pages": 4,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018",
    },
    {
        "id": "manufacturing-operations",
        "section_name": "Manufacturing & Operations",
        "display_order": 12,
        "description": "Manufacturing facilities, production capacity, supply chain, and operational processes.",
        "knowledge_mapping": [
            {"category": "operations", "fields": ["manufacturing_locations", "production_capacity", "utilization_rate", "supply_chain", "raw_materials"]},
        ],
        "validation_rules": [
            {"field": "operations.manufacturing_locations", "required": False, "description": "Manufacturing facility locations"},
            {"field": "operations.production_capacity", "required": False, "description": "Production capacity"},
        ],
        "prompt_template_path": "prompts/manufacturing-operations.md",
        "output_format": "markdown",
        "dependencies": ["business-overview"],
        "estimated_pages": 3,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018",
    },
    {
        "id": "properties-facilities",
        "section_name": "Properties & Facilities",
        "display_order": 13,
        "description": "Owned and leased properties, office locations, warehouses, and facilities.",
        "knowledge_mapping": [
            {"category": "assets", "fields": ["owned_properties", "leased_properties", "office_locations", "warehouses"]},
        ],
        "validation_rules": [
            {"field": "assets.owned_properties", "required": False, "description": "Owned properties"},
            {"field": "company.registered_address", "required": True, "description": "Registered office address"},
        ],
        "prompt_template_path": "prompts/properties-facilities.md",
        "output_format": "markdown",
        "dependencies": ["company-overview"],
        "estimated_pages": 2,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018",
    },
    {
        "id": "regulatory-environment",
        "section_name": "Regulatory Environment",
        "display_order": 14,
        "description": "Key regulations, licenses, and regulatory compliance affecting the business.",
        "knowledge_mapping": [
            {"category": "compliance", "fields": ["key_regulations", "licenses", "regulatory_bodies", "compliance_status"]},
            {"category": "industry", "fields": ["regulatory_framework"]},
        ],
        "validation_rules": [
            {"field": "compliance.licenses", "required": True, "description": "Key licenses and permits"},
            {"field": "compliance.key_regulations", "required": False, "description": "Applicable regulations"},
        ],
        "prompt_template_path": "prompts/regulatory-environment.md",
        "output_format": "markdown",
        "dependencies": ["industry-overview"],
        "estimated_pages": 3,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018",
    },
    {
        "id": "mda",
        "section_name": "Management Discussion & Analysis",
        "display_order": 15,
        "description": "Management perspective on financial results, business performance, outlook, and key risks.",
        "knowledge_mapping": [
            {"category": "financials", "fields": ["revenue", "net_profit", "ebitda", "ebitda_margin", "revenue_growth", "financial_year"]},
            {"category": "operations", "fields": ["operational_highlights"]},
            {"category": "risk", "fields": ["business_risks", "financial_risks"]},
        ],
        "validation_rules": [
            {"field": "financials.revenue", "required": True, "description": "Revenue figures"},
            {"field": "financials.net_profit", "required": True, "description": "Net profit/loss"},
            {"field": "financials.ebitda", "required": False, "description": "EBITDA"},
        ],
        "prompt_template_path": "prompts/mda.md",
        "output_format": "markdown",
        "dependencies": ["financial-information"],
        "estimated_pages": 6,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018 – Schedule VIII, Part A(18)",
    },
    {
        "id": "directors-kmp",
        "section_name": "Directors & Key Management Personnel",
        "display_order": 16,
        "description": "Profiles of the Board of Directors and Key Management Personnel including qualifications, experience, and compensation.",
        "knowledge_mapping": [
            {"category": "management", "fields": ["directors", "kmp", "board_committees", "director_compensation", "din_details"]},
        ],
        "validation_rules": [
            {"field": "management.directors", "required": True, "description": "Board of Directors list"},
            {"field": "management.kmp", "required": True, "description": "Key Management Personnel"},
        ],
        "prompt_template_path": "prompts/directors-kmp.md",
        "output_format": "markdown",
        "dependencies": [],
        "estimated_pages": 5,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018 – Schedule VIII, Part A(12)",
    },
    {
        "id": "promoters",
        "section_name": "Promoters",
        "display_order": 17,
        "description": "Details of promoters and promoter group including background, shareholding, and lock-in period.",
        "knowledge_mapping": [
            {"category": "promoters", "fields": ["promoter_names", "promoter_background", "promoter_shareholding", "lock_in_period", "group_entities"]},
        ],
        "validation_rules": [
            {"field": "promoters.promoter_names", "required": True, "description": "Promoter names"},
            {"field": "promoters.promoter_shareholding", "required": True, "description": "Promoter shareholding"},
        ],
        "prompt_template_path": "prompts/promoters.md",
        "output_format": "markdown",
        "dependencies": [],
        "estimated_pages": 3,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018 – Reg. 36",
    },
    {
        "id": "shareholding-pattern",
        "section_name": "Shareholding Pattern",
        "display_order": 18,
        "description": "Pre and post-issue shareholding pattern including promoters, public, and institutional holdings.",
        "knowledge_mapping": [
            {"category": "shareholding", "fields": ["pre_issue_shareholding", "post_issue_shareholding", "promoter_holding", "public_holding", "institutional_holding"]},
        ],
        "validation_rules": [
            {"field": "shareholding.pre_issue_shareholding", "required": True, "description": "Pre-issue shareholding"},
            {"field": "shareholding.post_issue_shareholding", "required": True, "description": "Post-issue shareholding"},
        ],
        "prompt_template_path": "prompts/shareholding-pattern.md",
        "output_format": "markdown",
        "dependencies": ["capital-structure"],
        "estimated_pages": 2,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018 – Reg. 36",
    },
    {
        "id": "capital-structure",
        "section_name": "Capital Structure",
        "display_order": 19,
        "description": "Details of authorized and paid-up share capital, share history, and post-issue capital.",
        "knowledge_mapping": [
            {"category": "company", "fields": ["authorized_capital", "paid_up_capital"]},
            {"category": "issue", "fields": ["fresh_issue_shares", "issue_price", "face_value"]},
            {"category": "shareholding", "fields": ["total_shares"]},
        ],
        "validation_rules": [
            {"field": "company.authorized_capital", "required": True, "description": "Authorized share capital"},
            {"field": "company.paid_up_capital", "required": True, "description": "Paid-up share capital"},
        ],
        "prompt_template_path": "prompts/capital-structure.md",
        "output_format": "markdown",
        "dependencies": [],
        "estimated_pages": 2,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018",
    },
    {
        "id": "financial-information",
        "section_name": "Financial Information",
        "display_order": 20,
        "description": "Audited financial statements including Balance Sheet, P&L, Cash Flow, and key financial ratios for last 3 years.",
        "knowledge_mapping": [
            {"category": "financials", "fields": ["balance_sheet", "pnl", "cash_flow", "notes_to_accounts", "financial_ratios", "revenue", "net_profit", "total_assets", "net_worth", "eps", "roe"]},
        ],
        "validation_rules": [
            {"field": "financials.revenue", "required": True, "description": "Revenue from operations"},
            {"field": "financials.net_profit", "required": True, "description": "Net profit/loss after tax"},
            {"field": "financials.balance_sheet", "required": True, "description": "Balance sheet data"},
            {"field": "financials.cash_flow", "required": True, "description": "Cash flow statement"},
            {"field": "financials.eps", "required": False, "description": "Earnings per share"},
        ],
        "prompt_template_path": "prompts/financial-information.md",
        "output_format": "markdown",
        "dependencies": [],
        "estimated_pages": 12,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018 – Schedule VIII, Part A(21)",
    },
    {
        "id": "objects-of-issue",
        "section_name": "Objects of the Issue",
        "display_order": 21,
        "description": "Purpose and utilization plan for the funds raised through the IPO.",
        "knowledge_mapping": [
            {"category": "issue", "fields": ["objects_of_issue", "fresh_issue_amount", "capex_plan", "working_capital_requirement", "general_corporate_purposes"]},
        ],
        "validation_rules": [
            {"field": "issue.objects_of_issue", "required": True, "description": "Objects of the issue"},
            {"field": "issue.fresh_issue_amount", "required": True, "description": "Fresh issue amount"},
        ],
        "prompt_template_path": "prompts/objects-of-issue.md",
        "output_format": "markdown",
        "dependencies": ["issue-summary"],
        "estimated_pages": 4,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018 – Reg. 7(1)",
    },
    {
        "id": "issue-details",
        "section_name": "Issue Details",
        "display_order": 22,
        "description": "Complete details of the issue including structure, timelines, allocation, and payment schedule.",
        "knowledge_mapping": [
            {"category": "issue", "fields": ["issue_type", "issue_size", "fresh_issue", "offer_for_sale", "price_band", "lot_size", "issue_dates", "allocation_structure"]},
            {"category": "exchange", "fields": ["exchange_name"]},
        ],
        "validation_rules": [
            {"field": "issue.issue_size", "required": True, "description": "Total issue size"},
            {"field": "issue.price_band", "required": False, "description": "Price band"},
            {"field": "issue.lot_size", "required": True, "description": "Minimum lot size"},
        ],
        "prompt_template_path": "prompts/issue-details.md",
        "output_format": "markdown",
        "dependencies": ["capital-structure"],
        "estimated_pages": 5,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018",
    },
    {
        "id": "dividend-policy",
        "section_name": "Dividend Policy",
        "display_order": 23,
        "description": "Company's dividend policy, past dividend history, and future dividend outlook.",
        "knowledge_mapping": [
            {"category": "financials", "fields": ["dividend_history", "dividend_per_share", "dividend_policy", "payout_ratio"]},
        ],
        "validation_rules": [
            {"field": "financials.dividend_policy", "required": False, "description": "Stated dividend policy"},
            {"field": "financials.dividend_history", "required": False, "description": "Historical dividends paid"},
        ],
        "prompt_template_path": "prompts/dividend-policy.md",
        "output_format": "markdown",
        "dependencies": ["financial-information"],
        "estimated_pages": 1,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018",
    },
    {
        "id": "related-party-transactions",
        "section_name": "Related Party Transactions",
        "display_order": 24,
        "description": "Disclosure of all material transactions with related parties as per Ind AS 24.",
        "knowledge_mapping": [
            {"category": "transactions", "fields": ["related_parties", "rpt_nature", "rpt_amounts", "rpt_terms", "outstanding_balances"]},
        ],
        "validation_rules": [
            {"field": "transactions.related_parties", "required": True, "description": "Related party list"},
            {"field": "transactions.rpt_amounts", "required": True, "description": "Transaction amounts"},
        ],
        "prompt_template_path": "prompts/related-party-transactions.md",
        "output_format": "markdown",
        "dependencies": ["financial-information"],
        "estimated_pages": 3,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018 – Reg. 32",
    },
    {
        "id": "outstanding-litigation",
        "section_name": "Outstanding Litigation",
        "display_order": 25,
        "description": "Disclosure of all pending legal proceedings against the company, directors, and promoters.",
        "knowledge_mapping": [
            {"category": "litigation", "fields": ["pending_cases", "criminal_cases", "civil_cases", "tax_disputes", "regulatory_actions", "material_litigations"]},
        ],
        "validation_rules": [
            {"field": "litigation.pending_cases", "required": True, "description": "Number of pending cases"},
            {"field": "litigation.material_litigations", "required": False, "description": "Materiality threshold for disclosure"},
        ],
        "prompt_template_path": "prompts/outstanding-litigation.md",
        "output_format": "markdown",
        "dependencies": [],
        "estimated_pages": 5,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018 – Schedule VIII, Part A(16)",
    },
    {
        "id": "material-contracts",
        "section_name": "Material Contracts",
        "display_order": 26,
        "description": "Summary of material contracts not entered into in the ordinary course of business.",
        "knowledge_mapping": [
            {"category": "contracts", "fields": ["material_contracts", "key_agreements", "joint_ventures", "partnerships"]},
        ],
        "validation_rules": [
            {"field": "contracts.material_contracts", "required": False, "description": "Material contracts list"},
        ],
        "prompt_template_path": "prompts/material-contracts.md",
        "output_format": "markdown",
        "dependencies": [],
        "estimated_pages": 2,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018 – Schedule VIII, Part B(1)",
    },
    {
        "id": "government-approvals",
        "section_name": "Government Approvals",
        "display_order": 27,
        "description": "All government and regulatory approvals, licenses, and permits obtained and pending.",
        "knowledge_mapping": [
            {"category": "compliance", "fields": ["licenses", "government_approvals", "pending_approvals", "license_renewals"]},
        ],
        "validation_rules": [
            {"field": "compliance.licenses", "required": True, "description": "Operating licenses"},
            {"field": "compliance.government_approvals", "required": False, "description": "Government approvals"},
        ],
        "prompt_template_path": "prompts/government-approvals.md",
        "output_format": "markdown",
        "dependencies": [],
        "estimated_pages": 2,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018",
    },
    {
        "id": "statutory-information",
        "section_name": "Statutory Information",
        "display_order": 28,
        "description": "Statutory disclosures, stock market data, and other mandatory information.",
        "knowledge_mapping": [
            {"category": "company", "fields": ["company_name", "cin", "registered_address", "auditor"]},
            {"category": "compliance", "fields": ["statutory_auditor", "cost_auditor", "secretarial_auditor"]},
        ],
        "validation_rules": [
            {"field": "company.cin", "required": True, "description": "CIN"},
            {"field": "compliance.statutory_auditor", "required": True, "description": "Statutory auditor details"},
        ],
        "prompt_template_path": "prompts/statutory-information.md",
        "output_format": "markdown",
        "dependencies": [],
        "estimated_pages": 2,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018",
    },
    {
        "id": "declaration",
        "section_name": "Declaration",
        "display_order": 29,
        "description": "Declarations and certifications by the Board of Directors and other signatories.",
        "knowledge_mapping": [
            {"category": "management", "fields": ["directors", "director_signatures"]},
            {"category": "company", "fields": ["company_name", "registered_address"]},
        ],
        "validation_rules": [
            {"field": "management.directors", "required": True, "description": "Director list for signing"},
        ],
        "prompt_template_path": "prompts/declaration.md",
        "output_format": "markdown",
        "dependencies": [],
        "estimated_pages": 1,
        "sebi_reference": "SEBI (ICDR) Regulations, 2018 – Schedule VIII, Part C",
    },
]


if __name__ == "__main__":
    for tpl in TEMPLATES:
        path = os.path.join(TEMPLATES_DIR, f"{tpl['id']}.yaml")
        with open(path, "w", encoding="utf-8") as f:
            yaml.dump(tpl, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
        print(f"Created: {path}")
